functionsDirectory = "D:\\00 CLAUDE APPS\\TodaRide- version5B\\netlify\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "D:\\00 CLAUDE APPS\\TodaRide- version5B\\dist"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"
functions = "D:\\00 CLAUDE APPS\\TodaRide- version5B\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]